# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uav.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uav.proto',
  package='uav',
  serialized_pb='\n\tuav.proto\x12\x03uav\"N\n\x03GPS\x12\x12\n\ntime_stamp\x18\x01 \x02(\t\x12\x11\n\tlongitude\x18\x02 \x02(\x02\x12\x10\n\x08latitude\x18\x03 \x02(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\",\n\x06Height\x12\x12\n\ntime_stamp\x18\x01 \x02(\t\x12\x0e\n\x06height\x18\x02 \x02(\x02\"<\n\tGyroscope\x12\x12\n\ntime_stamp\x18\x01 \x02(\t\x12\r\n\x05pitch\x18\x02 \x02(\x02\x12\x0c\n\x04roll\x18\x03 \x02(\x02\"D\n\rAccelerometer\x12\x12\n\ntime_stamp\x18\x01 \x02(\t\x12\t\n\x01x\x18\x02 \x02(\x02\x12\t\n\x01y\x18\x03 \x02(\x02\x12\t\n\x01z\x18\x04 \x02(\x02\"\x97\x01\n\x0c\x44ronePackage\x12\x12\n\ntime_stamp\x18\x01 \x02(\t\x12\x15\n\x03gps\x18\x02 \x02(\x0b\x32\x08.uav.GPS\x12\x1b\n\x06height\x18\x03 \x02(\x0b\x32\x0b.uav.Height\x12\x1c\n\x04gyro\x18\x04 \x02(\x0b\x32\x0e.uav.Gyroscope\x12!\n\x05\x61\x63\x63\x65l\x18\x05 \x02(\x0b\x32\x12.uav.Accelerometer')




_GPS = _descriptor.Descriptor(
  name='GPS',
  full_name='uav.GPS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='uav.GPS.time_stamp', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='uav.GPS.longitude', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='uav.GPS.latitude', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='uav.GPS.height', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=96,
)


_HEIGHT = _descriptor.Descriptor(
  name='Height',
  full_name='uav.Height',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='uav.Height.time_stamp', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='uav.Height.height', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=98,
  serialized_end=142,
)


_GYROSCOPE = _descriptor.Descriptor(
  name='Gyroscope',
  full_name='uav.Gyroscope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='uav.Gyroscope.time_stamp', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='uav.Gyroscope.pitch', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roll', full_name='uav.Gyroscope.roll', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=144,
  serialized_end=204,
)


_ACCELEROMETER = _descriptor.Descriptor(
  name='Accelerometer',
  full_name='uav.Accelerometer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='uav.Accelerometer.time_stamp', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='uav.Accelerometer.x', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='uav.Accelerometer.y', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='uav.Accelerometer.z', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=206,
  serialized_end=274,
)


_DRONEPACKAGE = _descriptor.Descriptor(
  name='DronePackage',
  full_name='uav.DronePackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='uav.DronePackage.time_stamp', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps', full_name='uav.DronePackage.gps', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='uav.DronePackage.height', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gyro', full_name='uav.DronePackage.gyro', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accel', full_name='uav.DronePackage.accel', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=277,
  serialized_end=428,
)

_DRONEPACKAGE.fields_by_name['gps'].message_type = _GPS
_DRONEPACKAGE.fields_by_name['height'].message_type = _HEIGHT
_DRONEPACKAGE.fields_by_name['gyro'].message_type = _GYROSCOPE
_DRONEPACKAGE.fields_by_name['accel'].message_type = _ACCELEROMETER
DESCRIPTOR.message_types_by_name['GPS'] = _GPS
DESCRIPTOR.message_types_by_name['Height'] = _HEIGHT
DESCRIPTOR.message_types_by_name['Gyroscope'] = _GYROSCOPE
DESCRIPTOR.message_types_by_name['Accelerometer'] = _ACCELEROMETER
DESCRIPTOR.message_types_by_name['DronePackage'] = _DRONEPACKAGE

class GPS(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GPS

  # @@protoc_insertion_point(class_scope:uav.GPS)

class Height(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEIGHT

  # @@protoc_insertion_point(class_scope:uav.Height)

class Gyroscope(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GYROSCOPE

  # @@protoc_insertion_point(class_scope:uav.Gyroscope)

class Accelerometer(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACCELEROMETER

  # @@protoc_insertion_point(class_scope:uav.Accelerometer)

class DronePackage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DRONEPACKAGE

  # @@protoc_insertion_point(class_scope:uav.DronePackage)


# @@protoc_insertion_point(module_scope)
